import React, { useState } from 'react';
import { useMaintenanceStore } from '../store/useMaintenanceStore';
import { useMapStore } from '../store/useMapStore';
import { KineticMap } from '../components/KineticMap/KineticMap';
import './SimulationSandbox.css';

const SimulationSandbox: React.FC = () => {
    const { activeBlocks, removeBlockRemote, openDrawer } = useMaintenanceStore();
    const { trainStates } = useMapStore();
    const blockList = Array.from(activeBlocks.values());

    const [delayTrainId, setDelayTrainId] = useState(trainStates[0]?.train_id || 'TR-8829-X');
    const [latency, setLatency] = useState(15);
    const [isRecalculating, setIsRecalculating] = useState(false);
    const [recalculatedForTrain, setRecalculatedForTrain] = useState<string | null>(null);
    const [impact, setImpact] = useState({ reliability: '-12.4%', congestion: '+85%' });
    const [adjustments, setAdjustments] = useState<{id: number, type: string, desc: string, train_id?: string, edge_id?: string, constraint_type?: string, value?: number}[]>([]);

    const handleRecalculate = async () => {
        setIsRecalculating(true);
        try {
            const res = await fetch('http://localhost:8000/api/v1/simulation/analyze', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    delay_train_id: delayTrainId,
                    latency_minutes: latency,
                })
            });

            if (!res.ok) throw new Error(`Server error: ${res.status}`);

            const data = await res.json();

            // Real deterministic impact scores from RL + OR-Tools
            setImpact({
                reliability: data.impact.reliability,
                congestion: data.impact.congestion,
            });

            // Real adjustments generated by the AI pipeline
            setAdjustments(data.adjustments || []);
            setRecalculatedForTrain(delayTrainId);
        } catch (err) {
            console.error('[Sandbox] Analysis failed:', err);
            // Fallback message so user knows something went wrong
            setAdjustments([{
                id: -1,
                type: 'Backend Unavailable',
                desc: 'Could not reach the simulation engine. Ensure the backend is running.'
            }]);
        } finally {
            setIsRecalculating(false);
        }
    };

    const handleDeploy = async () => {
        try {
            const payload = {
                blocks: blockList,
                constraints: adjustments.map(a => ({
                    id: `constraint-${Date.now()}-${a.id}`,
                    type: a.constraint_type || 'SPEED_LIMIT',
                    edge_id: a.edge_id || 'edge-1-2', 
                    value: a.value !== undefined ? a.value : 0,
                    expires_at: Math.floor(Date.now() / 1000) + 3600 // 1 hour TTL
                }))
            };
            
            const res = await fetch('http://localhost:8000/api/v1/simulation/deploy', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });
            
            if (res.ok) {
                alert('Simulation Sandbox Deployed Successfully!');
            } else {
                alert('Failed to deploy simulation.');
            }
        } catch (error) {
            console.error(error);
            alert('Error connecting to backend.');
        }
    };

    return (
        <div className="p-8 space-y-8">
            {/* Page Header */}
            <div className="flex justify-between items-end">
                <div>
                    <h1 className="text-3xl font-extrabold tracking-tight text-on-surface mb-2">Network Topology Sandbox</h1>
                    <p className="text-on-surface-variant max-w-2xl">Modify real-time network parameters and simulate cascading impacts across the fleet topology. Use the Marey chart to visualize time-distance dependencies.</p>
                </div>
                <div className="flex gap-3">
                    <button className="bg-surface-container text-on-primary-container px-6 py-2.5 rounded-lg font-['Plus_Jakarta_Sans'] font-semibold text-sm hover:opacity-90 transition-all">
                        Save Scenario
                    </button>
                    <button 
                        onClick={handleDeploy}
                        className="bg-[#8B5CF6] text-white px-6 py-2.5 rounded-lg font-['Plus_Jakarta_Sans'] font-semibold text-sm shadow-[0px_20px_40px_rgba(139,92,246,0.2)] hover:opacity-90 active:scale-95 transition-all">
                        Deploy to Fleet
                    </button>
                </div>
            </div>
            
            {/* Top Row: Map and Proposed Adjustments */}
            <div className="grid grid-cols-12 gap-8 mb-8">
                {/* Top Left: Live Sandbox Map */}
                <div className="col-span-12 lg:col-span-8">
                    <section className="bg-surface-container-lowest p-6 rounded-lg shadow-[0px_20px_40px_rgba(44,47,49,0.06)] h-full min-h-[600px] flex flex-col relative">
                        <h3 className="text-lg font-bold text-on-surface mb-4 flex items-center justify-between">
                            <span>Live Topology Map</span>
                            <span className="flex items-center gap-2 text-xs font-bold text-emerald-600 bg-emerald-100 px-3 py-1 rounded-full">
                                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                                LIVE
                            </span>
                        </h3>
                        <div className="flex-1 w-full bg-slate-900 rounded-xl mb-4 relative overflow-hidden">
                            <KineticMap />
                        </div>
                        <div className="space-y-3 shrink-0">
                            <div className="flex justify-between text-xs font-medium border-b border-surface-container pb-2">
                                <span className="text-slate-500">Active Node Count</span>
                                <span className="text-on-surface">1,492</span>
                            </div>
                            <div className="flex justify-between text-xs font-medium border-b border-surface-container pb-2">
                                <span className="text-slate-500">Critical Paths</span>
                                <span className="text-on-surface">18 Detected</span>
                            </div>
                            <div className="flex justify-between text-xs font-medium">
                                <span className="text-slate-500">Last Simulation</span>
                                <span className="text-on-surface">Just now</span>
                            </div>
                        </div>
                    </section>
                </div>
                
                {/* Top Right: Proposed Network Adjustments */}
                <div className="col-span-12 lg:col-span-4 flex flex-col">
                    <section className="bg-surface-container-lowest p-6 rounded-lg shadow-[0px_20px_40px_rgba(44,47,49,0.06)] h-full flex flex-col flex-1">
                        <h3 className="text-lg font-bold text-on-surface mb-4">Proposed Network Adjustments</h3>
                        <div className="space-y-4 overflow-y-auto flex-1 pb-4">
                            {adjustments.length === 0 ? (
                                <p className="text-sm text-slate-400 italic">No adjustments proposed yet. Click Recalculate Network to analyze.</p>
                            ) : (
                                adjustments.map((adj) => (
                                    <div key={adj.id} className="flex items-center justify-between p-4 bg-surface-container-low rounded-lg group hover:bg-violet-50 transition-colors">
                                        <div className="flex items-center gap-4">
                                            <div className="w-10 h-10 rounded-full bg-white flex items-center justify-center text-violet-500 shadow-sm">
                                                <span className="material-symbols-outlined">bolt</span>
                                            </div>
                                            <div>
                                                <p className="text-sm font-bold text-on-surface">{adj.type}</p>
                                                <p className="text-xs text-on-surface-variant">{adj.desc}</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-3">
                                            <span className="bg-violet-100 text-violet-700 px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-tight">Recommended</span>
                                            <button className="material-symbols-outlined text-violet-500">check_circle</button>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    </section>
                </div>
            </div>
            
            {/* Bottom Row: Control, What-If, Marey */}
            <div className="grid grid-cols-12 gap-8">
                {/* Bottom Left: Simulation Control */}
                <div className="col-span-12 lg:col-span-4 flex flex-col">
                    <section className="bg-surface-container-lowest p-6 rounded-lg shadow-[0px_20px_40px_rgba(44,47,49,0.06)] h-full">
                        <h3 className="text-lg font-bold text-on-surface mb-6 flex items-center gap-2">
                            <span className="material-symbols-outlined text-violet-500">settings_input_component</span>
                            Simulation Control
                        </h3>
                        <div className="space-y-6">
                            <div>
                                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Primary Delay Node</label>
                                <div className="relative">
                                    <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 z-10">train</span>
                                    <select 
                                        className="w-full pl-10 pr-10 py-3 bg-surface-container-low border-none rounded-sm font-mono text-sm focus:ring-2 focus:ring-violet-500/30 text-on-surface appearance-none cursor-pointer" 
                                        value={delayTrainId}
                                        onChange={e => setDelayTrainId(e.target.value)}
                                    >
                                        <option value="">Select a train...</option>
                                        {trainStates.map(t => (
                                            <option key={t.train_id} value={t.train_id}>{t.train_id}</option>
                                        ))}
                                    </select>
                                    <span className="material-symbols-outlined absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none">expand_more</span>
                                </div>
                                <p className="text-[11px] text-slate-400 mt-1.5">Enter Train ID to inject latency</p>
                            </div>
                            <div>
                                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Latency Duration (min)</label>
                                <input 
                                    className="w-full h-1.5 bg-surface-container rounded-lg appearance-none cursor-pointer accent-violet-500" 
                                    type="range" 
                                    min="0"
                                    max="60"
                                    value={latency}
                                    onChange={e => setLatency(parseInt(e.target.value))}
                                />
                                <div className="flex justify-between mt-2 text-xs font-medium text-on-surface-variant">
                                    <span>0</span>
                                    <span className="text-violet-600 font-bold">{latency} min</span>
                                    <span>60</span>
                                </div>
                            </div>
                            <div className="pt-4 border-t border-surface-container">
                                <button 
                                    onClick={handleRecalculate}
                                    disabled={isRecalculating}
                                    className="w-full bg-[#8B5CF6] text-white py-4 rounded-sm font-bold flex items-center justify-center gap-2 hover:opacity-90 active:scale-[0.98] transition-all disabled:opacity-50">
                                    <span className={`material-symbols-outlined ${isRecalculating ? 'animate-spin' : ''}`}>refresh</span>
                                    {isRecalculating ? 'Recalculating...' : 'Recalculate Network'}
                                </button>
                            </div>
                            
                            {/* Impact Analysis Scorecard */}
                            <div className="pt-4">
                                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-4">Impact Analysis</h4>
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="bg-surface-container-low p-4 rounded-lg transition-all duration-300">
                                        <p className="text-[10px] font-bold text-slate-500 uppercase">Reliability</p>
                                        <p className="text-2xl font-extrabold text-error">{impact.reliability}</p>
                                    </div>
                                    <div className="bg-surface-container-low p-4 rounded-lg transition-all duration-300">
                                        <p className="text-[10px] font-bold text-slate-500 uppercase">Congestion</p>
                                        <p className="text-2xl font-extrabold text-on-surface-variant">{impact.congestion}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                
                {/* Bottom Middle: What-If Maintenance Blocks */}
                <div className="col-span-12 lg:col-span-4 flex flex-col">
                    <section className="bg-surface-container-lowest rounded-lg shadow-[0px_20px_40px_rgba(44,47,49,0.06)] overflow-hidden flex-1">
                        <div className="sandbox-mms-panel h-full flex flex-col">
                            <div className="sandbox-mms-header">
                                <h3 className="sandbox-mms-title">
                                    <span className="material-symbols-outlined text-amber-500" style={{ fontSize: 18 }}>construction</span>
                                    What-If Maintenance Blocks
                                    {blockList.length > 0 && (
                                        <span className="sandbox-mms-count">{blockList.length} active</span>
                                    )}
                                </h3>
                                <button
                                    className="sandbox-mms-add-btn"
                                    onClick={() => openDrawer()}
                                >
                                    <span className="material-symbols-outlined" style={{ fontSize: 14 }}>add</span>
                                    Add Block
                                </button>
                            </div>

                            {blockList.length === 0 ? (
                                <div className="sandbox-mms-empty flex-1 flex flex-col items-center justify-center">
                                    <div className="sandbox-mms-empty-icon">🛤️</div>
                                    <p className="sandbox-mms-empty-text text-center">
                                        No maintenance blocks active.<br />Add a What-If block to simulate emergency repairs.
                                    </p>
                                </div>
                            ) : (
                                <div className="sandbox-block-list overflow-y-auto flex-1">
                                    {blockList.map((blk) => (
                                        <div
                                            key={blk.blockId}
                                            className={`sandbox-block-card ${blk.isWhatIf ? 'whatif' : ''}`}
                                        >
                                            <div className="sandbox-block-info">
                                                <span className="sandbox-block-id">{blk.element_id}</span>
                                                <div className="sandbox-block-meta">
                                                    <span
                                                        className={`sandbox-block-severity ${
                                                            blk.severity === 'TOTAL_BLOCK'
                                                                ? 'severity-total'
                                                                : 'severity-speed'
                                                        }`}
                                                    >
                                                        {blk.severity === 'TOTAL_BLOCK' ? '🔴 BLOCKED' : '🟡 RESTRICTED'}
                                                    </span>
                                                    <span>{blk.type}</span>
                                                    {blk.isWhatIf && <span style={{ color: '#d97706', fontWeight: 700 }}>WHAT-IF</span>}
                                                </div>
                                            </div>
                                            <button
                                                className="sandbox-block-toggle-btn"
                                                onClick={() => removeBlockRemote(blk.element_id)}
                                            >
                                                <span className="material-symbols-outlined" style={{ fontSize: 14 }}>close</span>
                                                Clear
                                            </button>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    </section>
                </div>
                
                {/* Bottom Right: Interactive Marey Topology */}
                <div className="col-span-12 lg:col-span-4 flex flex-col">
                    <section className="bg-surface-container-lowest p-6 rounded-lg shadow-[0px_20px_40px_rgba(44,47,49,0.06)] min-h-[350px] h-full flex flex-col">
                        <div className="flex justify-between items-center mb-6">
                            <h3 className="text-lg font-bold text-on-surface">Interactive Marey Topology</h3>
                            <div className="flex gap-2">
                                <span className="flex items-center gap-1.5 text-[11px] font-bold text-slate-500">
                                    <span className="w-2.5 h-2.5 rounded-full bg-[#8B5CF6]"></span> Projected
                                </span>
                                <span className="flex items-center gap-1.5 text-[11px] font-bold text-slate-500">
                                    <span className="w-2.5 h-2.5 rounded-full bg-slate-300"></span> Historical
                                </span>
                            </div>
                        </div>
                        
                        {/* Asymmetric Data Visualization Canvas */}
                        <div className="flex-1 relative bg-surface-container-low rounded-xl overflow-hidden p-4">
                            <div className="absolute inset-0 opacity-20 pointer-events-none" style={{ backgroundImage: "radial-gradient(#8B5CF6 0.5px, transparent 0.5px)", backgroundSize: "24px 24px" }}></div>
                            
                            {/* Marey SVG Content */}
                            {(() => {
                                const isRecalc = recalculatedForTrain === delayTrainId;
                                const yOffset = isRecalc ? latency * 2 : 0;
                                return (
                                    <svg className="w-full h-full" preserveAspectRatio="none" viewBox="0 0 800 400">
                                        {/* Axes */}
                                        <line stroke="#abadaf" strokeWidth="1" x1="40" x2="40" y1="20" y2="380"></line>
                                        <line stroke="#abadaf" strokeWidth="1" x1="40" x2="780" y1="380" y2="380"></line>
                                        
                                        {/* Network Lines */}
                                        <path 
                                            className="transition-all duration-1000 ease-in-out"
                                            d={`M 40 50 L 150 120 L 300 ${280 + yOffset} L 500 ${320 + yOffset * 0.5} L 780 370`} 
                                            fill="none" stroke={isRecalc ? "#f43f5e" : "#8B5CF6"} strokeWidth="3"
                                        />
                                        <path 
                                            className="transition-all duration-1000 ease-in-out delay-75"
                                            d={`M 40 100 L 200 180 L 400 ${220 + yOffset * 0.8} L 600 ${290 + yOffset * 0.4} L 780 330`} 
                                            fill="none" opacity="0.6" stroke={isRecalc ? "#f43f5e" : "#8B5CF6"} strokeWidth="3"
                                        />
                                        <path 
                                            className="transition-all duration-1000 ease-in-out delay-150"
                                            d={`M 40 150 L 250 250 L 550 ${310 + yOffset * 0.5} L 780 350`} 
                                            fill="none" opacity="0.3" stroke={isRecalc ? "#f43f5e" : "#8B5CF6"} strokeWidth="3"
                                        />
                                        
                                        {/* Nodes */}
                                        <circle cx="150" cy="120" fill="#8B5CF6" r="6"></circle>
                                        <circle 
                                            className="transition-all duration-1000 ease-in-out" 
                                            cx="300" cy={280 + yOffset} 
                                            fill={isRecalc ? "#f43f5e" : "#8B5CF6"} 
                                            r={isRecalc ? "10" : "8"}
                                        />
                                        <circle 
                                            className="transition-all duration-1000 ease-in-out" 
                                            cx="500" cy={320 + yOffset * 0.5} 
                                            fill={isRecalc ? "#f43f5e" : "#8B5CF6"} 
                                            r="6"
                                        />
                                        
                                        {/* Delay Bounds Overlay */}
                                        <path 
                                            className={`transition-all duration-1000 ease-in-out ${isRecalc ? 'opacity-100' : 'opacity-0'}`}
                                            d={`M 300 ${280 + yOffset} Q 400 ${350 + yOffset * 1.5} 500 ${320 + yOffset * 0.5}`} 
                                            fill="none" stroke="#b31b25" strokeDasharray="4" strokeWidth="2"
                                        />
                                        
                                        {/* Data Labels */}
                                        <text fill="#2c2f31" fontFamily="Inter" fontSize="10" fontWeight="600" x="50" y="40">Origin A</text>
                                        <text 
                                            className="transition-all duration-1000 ease-in-out"
                                            fill={isRecalc ? "#f43f5e" : "#2c2f31"} 
                                            fontFamily="Inter" fontSize="10" fontWeight="600" 
                                            x="280" y={isRecalc ? 260 + yOffset : 260}
                                        >
                                            Central Hub ({delayTrainId})
                                        </text>
                                    </svg>
                                );
                            })()}
                            
                            {/* Floating Glass Overlay Info */}
                            <div className="absolute bottom-6 left-6 bg-white/70 backdrop-blur-md p-4 rounded-lg border border-white shadow-xl max-w-xs transition-all duration-300">
                                <p className="text-xs font-bold text-violet-600 mb-1">Impact Highlight</p>
                                {recalculatedForTrain === delayTrainId ? (
                                    <p className="text-sm text-on-surface leading-tight font-medium">
                                        Recalculation complete. The {latency}m delay on {delayTrainId} causes cascading failures. AI has proposed adjustments below to prevent gridlock.
                                    </p>
                                ) : (
                                    <p className="text-sm text-on-surface leading-tight font-medium">
                                        Node {delayTrainId || 'selected train'} might cause critical bottlenecks at Central Hub. Recalculation advised.
                                    </p>
                                )}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default SimulationSandbox;
